cloud:
  aws:
    s3: #버킷이름
      bucket: superkurly-bucket
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
# multipartFile 용량 늘려주는 설정
spring:
  servlet:
    multipart:
      max-file-size: 1204MB
      max-request-size: 1204MB